CREATE TABLE `la_tenant_subscribe_send_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` int(11) DEFAULT '0' COMMENT '租户ID',
  `user_id` int(11) DEFAULT '0' COMMENT '用户ID',
  `openid` varchar(64) DEFAULT '' COMMENT '用户openid',
  `type` varchar(32) DEFAULT '' COMMENT '订阅类型：exam,countdown,version_update等',
  `related_id` int(11) DEFAULT '0' COMMENT '关联ID',
  `template_id` varchar(64) DEFAULT '' COMMENT '模板ID',
  `message_data` text COMMENT '消息内容数据',
  `send_status` tinyint(1) DEFAULT '0' COMMENT '发送状态：0-待发送，1-发送成功，2-发送失败',
  `send_time` int(11) DEFAULT NULL COMMENT '发送时间戳',
  `retry_times` tinyint(2) DEFAULT '0' COMMENT '重试次数',
  `error_code` int(11) DEFAULT '0' COMMENT '错误码',
  `error_msg` varchar(500) DEFAULT '' COMMENT '错误信息',
  `response_data` text COMMENT '微信返回的数据',
  `create_time` int(11) DEFAULT NULL COMMENT '创建时间',
  `update_time` int(11) DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `user_id` (`user_id`),
  KEY `type_related_id` (`type`, `related_id`),
  KEY `send_status` (`send_status`),
  KEY `send_time` (`send_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='租户订阅消息发送日志表';